# Generated by Django 4.2.5 on 2023-10-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_apcent_order_is_notificated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_apcent',
            new_name='is_abcent',
        ),
    ]
